//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBook.Properties.Languages {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectBook.Properties.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aluguel registrado com sucesso..
        /// </summary>
        internal static string AluguelRegistrado {
            get {
                return ResourceManager.GetString("AluguelRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atualiazando status dos alugueis....
        /// </summary>
        internal static string AtualizandoBancoDadosSpashScreen {
            get {
                return ResourceManager.GetString("AtualizandoBancoDadosSpashScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Banco de dados sincronizado com o OneDrive..
        /// </summary>
        internal static string BancoSincronizadoOneDrive {
            get {
                return ResourceManager.GetString("BancoSincronizadoOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Caminho do banco de dados:.
        /// </summary>
        internal static string CaminhoBanco {
            get {
                return ResourceManager.GetString("CaminhoBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente deletado com sucesso..
        /// </summary>
        internal static string ClienteDeletado {
            get {
                return ResourceManager.GetString("ClienteDeletado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este cliente não existe..
        /// </summary>
        internal static string ClienteNExiste {
            get {
                return ResourceManager.GetString("ClienteNExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente registrado com sucesso..
        /// </summary>
        internal static string ClienteRegistrado {
            get {
                return ResourceManager.GetString("ClienteRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário fazer uma conexão local com o banco de dados, indicando o caminho, para fazer a migração para o OneDrive..
        /// </summary>
        internal static string ConexaoLocalMigrarOneDrive {
            get {
                return ResourceManager.GetString("ConexaoLocalMigrarOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações salvas..
        /// </summary>
        internal static string ConfiguracoesSalvas {
            get {
                return ResourceManager.GetString("ConfiguracoesSalvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja realmente excluir {0}?.
        /// </summary>
        internal static string ConfirmarExcluisao1 {
            get {
                return ResourceManager.GetString("ConfirmarExcluisao1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja realmente excluir {0} alugado por {1}?.
        /// </summary>
        internal static string ConfirmarExclusao2 {
            get {
                return ResourceManager.GetString("ConfirmarExclusao2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja sair?.
        /// </summary>
        internal static string ConfirmarSair {
            get {
                return ResourceManager.GetString("ConfirmarSair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Uso de ícones de FAMFAMFAM: http://famfamfam.com.
        /// </summary>
        internal static string CreditosIcons {
            get {
                return ResourceManager.GetString("CreditosIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possivel conectar-se a base de dados: {0}. Deseja abrir a configurações?.
        /// </summary>
        internal static string ErrorConectarDb {
            get {
                return ResourceManager.GetString("ErrorConectarDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um error: {0}. Volte as configurações e crie uma novo string de conexão..
        /// </summary>
        internal static string ErrorMigrarOneDrive {
            get {
                return ResourceManager.GetString("ErrorMigrarOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um banco de dados sincronizado, deseja sobrescrever?.
        /// </summary>
        internal static string ExistePastaOneDrive {
            get {
                return ResourceManager.GetString("ExistePastaOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Está faltando arquivos escenciais para abrir o programa, tente reistalar-lo novamente..
        /// </summary>
        internal static string FaltaArquivoEscenciaisParaContinuar {
            get {
                return ResourceManager.GetString("FaltaArquivoEscenciaisParaContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informações atualizadas..
        /// </summary>
        internal static string InformacoesAtualizadas {
            get {
                return ResourceManager.GetString("InformacoesAtualizadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As informações estão incorretas..
        /// </summary>
        internal static string InformacoesIncorretasLogin {
            get {
                return ResourceManager.GetString("InformacoesIncorretasLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GNU General Public License v3.0.
        /// </summary>
        internal static string Licensa {
            get {
                return ResourceManager.GetString("Licensa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O livro ou o cliente não existem..
        /// </summary>
        internal static string LivroClienteNExistem {
            get {
                return ResourceManager.GetString("LivroClienteNExistem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Livro deletado com sucesso..
        /// </summary>
        internal static string LivroDeletado {
            get {
                return ResourceManager.GetString("LivroDeletado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este cliente não alugou este livro..
        /// </summary>
        internal static string LivroNAlugado {
            get {
                return ResourceManager.GetString("LivroNAlugado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este livro não foi alugado ou o cliente não alugou nenhum livro..
        /// </summary>
        internal static string LivroNAlugadoCliente {
            get {
                return ResourceManager.GetString("LivroNAlugadoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este livro não existe..
        /// </summary>
        internal static string LivroNExiste {
            get {
                return ResourceManager.GetString("LivroNExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Livro registrado com sucesso..
        /// </summary>
        internal static string LivroRegistrado {
            get {
                return ResourceManager.GetString("LivroRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Marque uma opção de busca para continuar..
        /// </summary>
        internal static string MarcarOpcao {
            get {
                return ResourceManager.GetString("MarcarOpcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Concluido.
        /// </summary>
        internal static string MessageBoxConcluido {
            get {
                return ResourceManager.GetString("MessageBoxConcluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error.
        /// </summary>
        internal static string MessageBoxError {
            get {
                return ResourceManager.GetString("MessageBoxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        internal static string MessageBoxExcluir {
            get {
                return ResourceManager.GetString("MessageBoxExcluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informação.
        /// </summary>
        internal static string MessageBoxInformacao {
            get {
                return ResourceManager.GetString("MessageBoxInformacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sobre.
        /// </summary>
        internal static string MessageBoxSobre {
            get {
                return ResourceManager.GetString("MessageBoxSobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Migrando para o OneDrive....
        /// </summary>
        internal static string MigrandoOneDrive {
            get {
                return ResourceManager.GetString("MigrandoOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você deseja migrar o banco de dados para seu OneDrive? Para que a sincronização funcione você deve estar com o aplicativo do OneDrive sempre atualizado..
        /// </summary>
        internal static string MigrarOneDriveExplicacao {
            get {
                return ResourceManager.GetString("MigrarOneDriveExplicacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Houve uma mudança na String de conexão, o programa será reiniciado..
        /// </summary>
        internal static string MudancaStringConexao {
            get {
                return ResourceManager.GetString("MudancaStringConexao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Preencha o cambo de busca..
        /// </summary>
        internal static string PreecherCampoBusca {
            get {
                return ResourceManager.GetString("PreecherCampoBusca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Preencha todos os campos obrigatórios..
        /// </summary>
        internal static string PreencherCamposObrigatorios {
            get {
                return ResourceManager.GetString("PreencherCamposObrigatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Procurando por atualizações....
        /// </summary>
        internal static string ProcurandoAtualizacoesSplashScreen {
            get {
                return ResourceManager.GetString("ProcurandoAtualizacoesSplashScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a String de conexão:.
        /// </summary>
        internal static string StringConexaoConfiguracoes {
            get {
                return ResourceManager.GetString("StringConexaoConfiguracoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Luan Roger© 2021.
        /// </summary>
        internal static string TheCreator {
            get {
                return ResourceManager.GetString("TheCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário deletado com sucesso..
        /// </summary>
        internal static string UsuarioDeletado {
            get {
                return ResourceManager.GetString("UsuarioDeletado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário registrado com sucesso..
        /// </summary>
        internal static string UsusarioRegistrado {
            get {
                return ResourceManager.GetString("UsusarioRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Realizando verificações de segurança....
        /// </summary>
        internal static string VerificacoesSegurancaSplashScreen {
            get {
                return ResourceManager.GetString("VerificacoesSegurancaSplashScreen", resourceCulture);
            }
        }
    }
}
