//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBook.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectBook.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddTextFile_16x {
            get {
                object obj = ResourceManager.GetObject("AddTextFile_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddUser_16x {
            get {
                object obj = ResourceManager.GetObject("AddUser_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alugado.
        /// </summary>
        internal static string aluguelStatus_Pendente {
            get {
                return ResourceManager.GetString("aluguelStatus_Pendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este livro não foi alugado ou o cliente não alugou nenhum livro..
        /// </summary>
        internal static string clienteLivroNaoAlugados {
            get {
                return ResourceManager.GetString("clienteLivroNaoAlugados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este cliente não está cadastrado, verifique se a informação de busca foi digitada corretamente..
        /// </summary>
        internal static string clienteNaoExiste_MessageBox {
            get {
                return ResourceManager.GetString("clienteNaoExiste_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluido.
        /// </summary>
        internal static string concluido_MessageBox {
            get {
                return ResourceManager.GetString("concluido_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações salvas..
        /// </summary>
        internal static string configuracoesSalvas_MessageBox {
            get {
                return ResourceManager.GetString("configuracoesSalvas_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente excluir.
        /// </summary>
        internal static string confirmarExclusao {
            get {
                return ResourceManager.GetString("confirmarExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alugado por .
        /// </summary>
        internal static string confirmarExclusaoAluguel2 {
            get {
                return ResourceManager.GetString("confirmarExclusaoAluguel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        internal static string confirmarExclusaoDe {
            get {
                return ResourceManager.GetString("confirmarExclusaoDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database_error_icon {
            get {
                object obj = ResourceManager.GetObject("database-error-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database_icon {
            get {
                object obj = ResourceManager.GetObject("database-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteAllRows_16x {
            get {
                object obj = ResourceManager.GetObject("DeleteAllRows_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteClause_16x {
            get {
                object obj = ResourceManager.GetObject("DeleteClause_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteUser_16x {
            get {
                object obj = ResourceManager.GetObject("DeleteUser_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit_grey_16x {
            get {
                object obj = ResourceManager.GetObject("Edit_grey_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error_MessageBox {
            get {
                return ResourceManager.GetString("error_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        internal static string excluir_MessageBox {
            get {
                return ResourceManager.GetString("excluir_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit_account {
            get {
                object obj = ResourceManager.GetObject("exit_account", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação.
        /// </summary>
        internal static string informacao_MessageBox {
            get {
                return ResourceManager.GetString("informacao_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As informações estão incorretas..
        /// </summary>
        internal static string informacoesIncorretas {
            get {
                return ResourceManager.GetString("informacoesIncorretas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key {
            get {
                object obj = ResourceManager.GetObject("key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Library_16x {
            get {
                object obj = ResourceManager.GetObject("Library_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LibrarySettings_16x {
            get {
                object obj = ResourceManager.GetObject("LibrarySettings_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este cliente não tem livro alugado..
        /// </summary>
        internal static string livroNaoAlugado {
            get {
                return ResourceManager.GetString("livroNaoAlugado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este livro não existe, verifique se a informação de busca foi digitada corretamente..
        /// </summary>
        internal static string livroNaoExiste_MessageBox {
            get {
                return ResourceManager.GetString("livroNaoExiste_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luan Roger© 2021.
        /// </summary>
        internal static string luanroger {
            get {
                return ResourceManager.GetString("luanroger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve uma mudança na String de conexão, o programa será reiniciado..
        /// </summary>
        internal static string mudancaConnectionString {
            get {
                return ResourceManager.GetString("mudancaConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O livro ou o cliente não existem..
        /// </summary>
        internal static string naoExisteLivroCliente {
            get {
                return ResourceManager.GetString("naoExisteLivroCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faça uma pesquisa para continuar..
        /// </summary>
        internal static string preencherCampoBusca_MessageBox {
            get {
                return ResourceManager.GetString("preencherCampoBusca_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha todos os campos para continuar..
        /// </summary>
        internal static string preencherCampos {
            get {
                return ResourceManager.GetString("preencherCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha todos os campos obrigatórios.
        /// </summary>
        internal static string preencherCamposObrigatorios_MessageBox {
            get {
                return ResourceManager.GetString("preencherCamposObrigatorios_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Print_16x {
            get {
                object obj = ResourceManager.GetObject("Print_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para que as alterações do banco de dados sejam aplicadas será nescessário reiniciar o programa. Desseja reiniciar?.
        /// </summary>
        internal static string reiniciarPrograma_MessageBox {
            get {
                return ResourceManager.GetString("reiniciarPrograma_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Search_16x {
            get {
                object obj = ResourceManager.GetObject("Search_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SearchGo_16x {
            get {
                object obj = ResourceManager.GetObject("SearchGo_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        internal static string sobre_MessageBox {
            get {
                return ResourceManager.GetString("sobre_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trash_16x {
            get {
                object obj = ResourceManager.GetObject("Trash_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UserGroup_16x {
            get {
                object obj = ResourceManager.GetObject("UserGroup_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° da versão: v.
        /// </summary>
        internal static string versao_MessageBox {
            get {
                return ResourceManager.GetString("versao_MessageBox", resourceCulture);
            }
        }
    }
}
