//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBook.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectBook.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap admin {
            get {
                object obj = ResourceManager.GetObject("admin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aluguel registrado com sucesso..
        /// </summary>
        internal static string AluguelRegistrado {
            get {
                return ResourceManager.GetString("AluguelRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atualização disponível.
        /// </summary>
        internal static string AtualizacaoDisponivel {
            get {
                return ResourceManager.GetString("AtualizacaoDisponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atualiazando status dos alugueis....
        /// </summary>
        internal static string AtualizandoBancoDados_SpashScreen {
            get {
                return ResourceManager.GetString("AtualizandoBancoDados_SpashScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aviso.
        /// </summary>
        internal static string Aviso_MessageBox {
            get {
                return ResourceManager.GetString("Aviso_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esta é provavelmente a conta de administrador padrão do programa, se deleta-la, certifique-se de possuir uma outra conta de administrador, Deseja continuar?.
        /// </summary>
        internal static string AvisoDeletarAdmin {
            get {
                return ResourceManager.GetString("AvisoDeletarAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Banco de dados sincronizado com o OneDrive..
        /// </summary>
        internal static string BancoSincronizadoOneDrive {
            get {
                return ResourceManager.GetString("BancoSincronizadoOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap book_add {
            get {
                object obj = ResourceManager.GetObject("book_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap book_delete {
            get {
                object obj = ResourceManager.GetObject("book_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap book_edit {
            get {
                object obj = ResourceManager.GetObject("book_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap book_go {
            get {
                object obj = ResourceManager.GetObject("book_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bullet_go {
            get {
                object obj = ResourceManager.GetObject("bullet_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Caminho do banco de dados:.
        /// </summary>
        internal static string CaminhoBanco {
            get {
                return ResourceManager.GetString("CaminhoBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Carregando....
        /// </summary>
        internal static string Carregando_SplashScreen {
            get {
                return ResourceManager.GetString("Carregando_SplashScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap client_add {
            get {
                object obj = ResourceManager.GetObject("client_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap client_delete {
            get {
                object obj = ResourceManager.GetObject("client_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap client_edit {
            get {
                object obj = ResourceManager.GetObject("client_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap client_go {
            get {
                object obj = ResourceManager.GetObject("client_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente deletado com sucesso..
        /// </summary>
        internal static string ClienteDeletado {
            get {
                return ResourceManager.GetString("ClienteDeletado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este livro não foi alugado ou o cliente não alugou nenhum livro..
        /// </summary>
        internal static string ClienteLivroNaoAlugados {
            get {
                return ResourceManager.GetString("ClienteLivroNaoAlugados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este cliente não está cadastrado, verifique se a informação de busca foi digitada corretamente..
        /// </summary>
        internal static string ClienteNaoCadastrado {
            get {
                return ResourceManager.GetString("ClienteNaoCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este cliente não existe..
        /// </summary>
        internal static string ClienteNaoExiste {
            get {
                return ResourceManager.GetString("ClienteNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente registrado com sucesso..
        /// </summary>
        internal static string ClienteRegistrado {
            get {
                return ResourceManager.GetString("ClienteRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cog_delete {
            get {
                object obj = ResourceManager.GetObject("cog_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Concluido.
        /// </summary>
        internal static string Concluido_MessageBox {
            get {
                return ResourceManager.GetString("Concluido_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário fazer uma conexão local com o banco de dados, indicando o caminho, para fazer a migração para o OneDrive..
        /// </summary>
        internal static string ConexaoLocalMigrarOneDrive {
            get {
                return ResourceManager.GetString("ConexaoLocalMigrarOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário fazer uma conexão local com o banco de dados, indicando o caminho, para fazer a migração para o OneDrive..
        /// </summary>
        internal static string ConexaoLocalNescessaria {
            get {
                return ResourceManager.GetString("ConexaoLocalNescessaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurações salvas..
        /// </summary>
        internal static string ConfiguracoesSalvas {
            get {
                return ResourceManager.GetString("ConfiguracoesSalvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja realmente excluir {0}.
        /// </summary>
        internal static string ConfirmarExclusao1 {
            get {
                return ResourceManager.GetString("ConfirmarExclusao1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja realmente excluir {0} alugado por {1}?.
        /// </summary>
        internal static string ConfirmarExclusao2 {
            get {
                return ResourceManager.GetString("ConfirmarExclusao2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja realmente sair?.
        /// </summary>
        internal static string ConfirmarSair {
            get {
                return ResourceManager.GetString("ConfirmarSair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você deseja criar uma cópia do banco de dados no OneDrive..
        /// </summary>
        internal static string CreateCopyOneDrive {
            get {
                return ResourceManager.GetString("CreateCopyOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ícones de FAMFAMFAM: http://famfamfam.com.
        /// </summary>
        internal static string CreditosIcones {
            get {
                return ResourceManager.GetString("CreditosIcones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database_error_icon {
            get {
                object obj = ResourceManager.GetObject("database-error-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database_icon {
            get {
                object obj = ResourceManager.GetObject("database-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap enter_account {
            get {
                object obj = ResourceManager.GetObject("enter_account", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error.
        /// </summary>
        internal static string Error_MessageBox {
            get {
                return ResourceManager.GetString("Error_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possivel conectar-se a base de dados. Deseja abrir a configurações?.
        /// </summary>
        internal static string ErrorConectarDb {
            get {
                return ResourceManager.GetString("ErrorConectarDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Houve um problema ao tentar conectar-se com o banco de dados, verifique a situação e tente novamente..
        /// </summary>
        internal static string ErrorFatalConectarDb {
            get {
                return ResourceManager.GetString("ErrorFatalConectarDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um error: {0}. Volte as configurações e crie uma novo string de conexão..
        /// </summary>
        internal static string ErrorMigrarOneDrive {
            get {
                return ResourceManager.GetString("ErrorMigrarOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Houve um error ao tentar recuperar o caminho do banco de dados..
        /// </summary>
        internal static string ErrorRecuperarCaminho {
            get {
                return ResourceManager.GetString("ErrorRecuperarCaminho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        internal static string Excluir_MessageBox {
            get {
                return ResourceManager.GetString("Excluir_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um banco de dados sincronizado, deseja sobrescrever?.
        /// </summary>
        internal static string ExistePastaOneDrive {
            get {
                return ResourceManager.GetString("ExistePastaOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit_account {
            get {
                object obj = ResourceManager.GetObject("exit_account", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Está faltando arquivos escenciais para abrir o programa, tente reistalar-lo novamente..
        /// </summary>
        internal static string FaltaArquivoEscenciais {
            get {
                return ResourceManager.GetString("FaltaArquivoEscenciais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código do livro digitado já existe..
        /// </summary>
        internal static string IdExistente {
            get {
                return ResourceManager.GetString("IdExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informação.
        /// </summary>
        internal static string Informacao_MessageBox {
            get {
                return ResourceManager.GetString("Informacao_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informações atualizadas.
        /// </summary>
        internal static string InformaçõesAtualizadas_MessageBox {
            get {
                return ResourceManager.GetString("InformaçõesAtualizadas_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As informações estão incorretas..
        /// </summary>
        internal static string InformacoesIncorretasLogin {
            get {
                return ResourceManager.GetString("InformacoesIncorretasLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InicioBackground {
            get {
                object obj = ResourceManager.GetObject("InicioBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InicioBackground2 {
            get {
                object obj = ResourceManager.GetObject("InicioBackground2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GNU General Public License v3.0.
        /// </summary>
        internal static string Licensa {
            get {
                return ResourceManager.GetString("Licensa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O livro ou o cliente não existem..
        /// </summary>
        internal static string LivroClienteNaoExistem {
            get {
                return ResourceManager.GetString("LivroClienteNaoExistem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Livro deletado com sucesso..
        /// </summary>
        internal static string LivroDeletado {
            get {
                return ResourceManager.GetString("LivroDeletado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este livro não foi alugado..
        /// </summary>
        internal static string LivroNaoAluguado {
            get {
                return ResourceManager.GetString("LivroNaoAluguado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este livro não existe..
        /// </summary>
        internal static string LivroNaoExiste {
            get {
                return ResourceManager.GetString("LivroNaoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Livro registrado com sucesso..
        /// </summary>
        internal static string LivroRegistrado {
            get {
                return ResourceManager.GetString("LivroRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Marque uma opção de busca para continuar..
        /// </summary>
        internal static string MarcarOpcaoBusca {
            get {
                return ResourceManager.GetString("MarcarOpcaoBusca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Migrando para o OneDrive....
        /// </summary>
        internal static string MigrandoOneDrive {
            get {
                return ResourceManager.GetString("MigrandoOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Houve uma mudança na String de conexão, o programa será reiniciado..
        /// </summary>
        internal static string MudancaConnectionString {
            get {
                return ResourceManager.GetString("MudancaConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_add {
            get {
                object obj = ResourceManager.GetObject("page_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_delete {
            get {
                object obj = ResourceManager.GetObject("page_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_edit {
            get {
                object obj = ResourceManager.GetObject("page_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_excel {
            get {
                object obj = ResourceManager.GetObject("page_excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_go {
            get {
                object obj = ResourceManager.GetObject("page_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pergunta.
        /// </summary>
        internal static string Pergunta_MessageBox {
            get {
                return ResourceManager.GetString("Pergunta_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Faça uma pesquisa para continuar..
        /// </summary>
        internal static string PesquiseParaContinuar {
            get {
                return ResourceManager.GetString("PesquiseParaContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Preencha todos os campos obrigatórios.
        /// </summary>
        internal static string PreencherCamposObrigatorios {
            get {
                return ResourceManager.GetString("PreencherCamposObrigatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Icon semelhante a (Ícone).
        /// </summary>
        internal static System.Drawing.Icon PrinteIcons {
            get {
                object obj = ResourceManager.GetObject("PrinteIcons", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printer {
            get {
                object obj = ResourceManager.GetObject("printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Procurando por atualizações....
        /// </summary>
        internal static string ProcurandoAtualizacoes_SplashScreen {
            get {
                return ResourceManager.GetString("ProcurandoAtualizacoes_SplashScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProjectBookIcon {
            get {
                object obj = ResourceManager.GetObject("ProjectBookIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As configurações serão redefinidas e o programa será reiniciado, deseja continuar?.
        /// </summary>
        internal static string RedefinirConfig {
            get {
                return ResourceManager.GetString("RedefinirConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Para que as alterações do banco de dados sejam aplicadas será nescessário reiniciar o programa. Desseja reiniciar?.
        /// </summary>
        internal static string ReiniciarPrograma {
            get {
                return ResourceManager.GetString("ReiniciarPrograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sobre.
        /// </summary>
        internal static string Sobre_MessageBox {
            get {
                return ResourceManager.GetString("Sobre_MessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SplashScreen {
            get {
                object obj = ResourceManager.GetObject("SplashScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a String de conexão:.
        /// </summary>
        internal static string StringConexao {
            get {
                return ResourceManager.GetString("StringConexao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap table {
            get {
                object obj = ResourceManager.GetObject("table", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap textfield {
            get {
                object obj = ResourceManager.GetObject("textfield", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LuanRoger© 2021.
        /// </summary>
        internal static string TheCreator {
            get {
                return ResourceManager.GetString("TheCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor digitado em {0} não pode ser um carácter.
        /// </summary>
        internal static string TypeError {
            get {
                return ResourceManager.GetString("TypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a URL do projeto: https://github.com/LuanRoger/ProjectBook.
        /// </summary>
        internal static string UrlProjeto {
            get {
                return ResourceManager.GetString("UrlProjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Icon semelhante a (Ícone).
        /// </summary>
        internal static System.Drawing.Icon UserGrayIcons {
            get {
                object obj = ResourceManager.GetObject("UserGrayIcons", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário deletado com sucesso..
        /// </summary>
        internal static string UsuarioDeletado {
            get {
                return ResourceManager.GetString("UsuarioDeletado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário cadastrado com sucesso..
        /// </summary>
        internal static string UsuarioRegistrado {
            get {
                return ResourceManager.GetString("UsuarioRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Realizando verificações de segurança....
        /// </summary>
        internal static string VerificacoesSeguranca_SplashScreen {
            get {
                return ResourceManager.GetString("VerificacoesSeguranca_SplashScreen", resourceCulture);
            }
        }
    }
}
